const Discord = require('discord.js');

function convertToMiliseconds(number) {
  if (number.includes('mins')) {
    const numberNoText = number.replace('mins', '')
    return (numberNoText * 60) * 1000
  } else {
    return number * 1000
  }
}

function embedMessage (options) {
  const setOptions = (
    {
    color = '#0099ff',
    title = '',
    url = 'https://discord.js.org/',
    author = 'Fit Bot',
    authorImage = 'https://i.imgur.com/wv7kGlF.jpg',
    authorLink = '',
    description = '',
    fields = [],
    thumbnail = 'https://i.imgur.com/wv7kGlF.jpg',
    image = '',
    footer= 'Generated by Fit Bot',
    footerImage = 'https://i.imgur.com/wv7kGlF.jpg'
  }) => {
    return {
      color,
      title,
      url,
      author,
      authorImage,
      authorLink,
      description,
      fields,
      thumbnail,
      image,
      footer,
      footerImage
    }
  }
  
  // { name: 'Regular field title', value: 'Some value here' },
  // { name: '\u200B', value: '\u200B' },
  // { name: 'Inline field title', value: 'Some value here', inline: true },
  // { name: 'Inline field title', value: 'Some value here', inline: true },

  const messageOptions = setOptions(options);

  return new Discord.MessageEmbed()
  .setColor(messageOptions.color)
	.setTitle(messageOptions.title)
	.setURL(messageOptions.url)
	.setAuthor(messageOptions.author, messageOptions.authorImage, messageOptions.authorLink)
	.setDescription(messageOptions.description)
	.setThumbnail(messageOptions.thumbnail)
	.addFields(messageOptions.fields)
	.setImage(messageOptions.image)
	.setTimestamp()
	.setFooter(messageOptions.footer, messageOptions.footerImage);
}

module.exports = {
  convertToMiliseconds,
  embedMessage
}